spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cats_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate-dialect: org.hibernate.dialect.MySQLDialect
#      hibernate.format_sql: true
#    show-sql: true

  zipkin:
    base-url: http://zipkin:9411/
    collector:
      host: zipkin

#  sleuth:
#    sampler:
#      probability: 1.0

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
