networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cats_db
    networks:
      - mynet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 1